### ISSUE TITLE
[EPIC] As a PLAYER I want to have proper leveling system so that I can be constantly challenged and be kept in the flow channel 

### ISSUE THREAD

**Issue by chektien** [ict2105-csc2007/eod#4]
This is a major undertaking to design and create a levelling system.

- [ ] Completed design of the system
- [ ] Implemented level 1: Tutorial
- [ ] Implemented level 2: Intro core gameplay mechanic of steps to HP
- [ ] Implemented level 3: Intro survival gameplay mechanic
- [ ] Implemented level 4: Intro battle gameplay mechanic
- [ ] Implemented level 5: Intro boss gameplay mechanic
- [ ] ...
